spring:
  # redis相关配置
  redis:
    host: 192.168.64.101
    port: 6379
    password: 4321
    database: 0 # 提供16个数据库,操作0
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: 1ms # 连接池最大阻塞等待时间
        max-idle: 4 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接